### ISSUE TITLE
Add minimal external service monitoring

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/ops#2]
minimal external checks to make sure our stuff is in the world.
- A DNS check and
- a http://hostname check
  should be sufficient.

Which provider?
- [Pingdom](https://www.pingdom.com/)
- Route53: http://aws.amazon.com/route53/pricing/#Health_Checks

**Comment by rex** [comment]
I can't believe I didn't get this memo, but... I just learned that NewRelic released a *completely free* server monitoring product. 

https://blog.newrelic.com/2011/11/08/server-monitoring-is-here/
http://newrelic.com/server-monitoring

NewRelic for any other type of monitoring is incredibly expensive, but apparently this is completely free. Given NewRelic's incredible track record, I think we should give it a try. Especially since it's free.

**Comment by rex** [comment]
Update: I have two ping monitors created on NewRelic Synthetics, one for each of the above URLs listed. Each monitor is running every 5 minutes from 5 locations and failures will trigger email alerts to `alerts@chefbrigade.io`. 

I'm going to preliminarily close this issue but will reopen it if the current solution isn't working out.

**Comment by josephholsten** [comment]
Need docs for accessing it. where is it, what's our account name, &c

**Comment by rex** [comment]
@josephholsten I used my personal NewRelic account to set it up, absentmindedly. I will create a *new* NewRelic account for the organization and add the credentials to 1Password.

**Comment by josephholsten** [comment]
wint
